--------------------------------
-- COLORS
--------------------------------
BLACK       = {  0,   0,   0}
OFFBLACK    = { 45,  45,  45}
WHITE       = {255, 255, 255}
OFFWHITE    = {236, 240, 241}
LIGHTGREY   = {189, 195, 199}
GREY        = {149, 165, 166}
DARKGREY    = {127, 140, 141}
LIGHTBLUE   = { 52, 152, 219}
DARKBLUE    = { 41, 128, 185}
DARKRED     = {192,  57,  43}
LIGHTRED    = {231,  76,  60}
YELLOW      = {241, 196,  15}

MIDNIGHTBLUE = {44, 62, 80}
WETASPHALT   = {52, 73, 94}
NEPHRITIS    = {39, 174, 96}
EMERALD      = {46, 204, 113}
TURQOUISE    = {26, 188, 156}
GREENSEA     = {22, 160, 133}
ASBESTOS     = {127, 140, 141}
SILVER       = {189, 195, 199}
LIGHTSILVER  = {218,224,230}



DEBUGVISIBLECOLOR = OFFBLACK--EMERALD
-- background
BG = OFFWHITE

SHADOW_COLOR = LIGHTSILVER


-- Menu
BUTTON_ZISE = 48 -- square
PADDING = 6
MENUBG = MIDNIGHTBLUE
BUTTON_COLOR = GREENSEA
BUTTON_COLOR_ACTIVE = TURQOUISE
BUTTONCOLUMNS = 1

-- zoom strength
ZOOM_DEFAULT = 2
ZOOM_STRENGTH = 0.25
ZOOM_MAXIMUM = 4
ZOOM_MINIMUM = 1--0.5

--------------------------------
--  POINT 
--------------------------------

POINT_GRAB_DIST = 5 

POINT_MARKED_SIZE = POINT_GRAB_DIST
POINT_MARKED_COLOR = OFFBLACK--LIGHTGREY 
POINT_SIZE = 1 --radius 
POINT_COLOR = ASBESTOS--OFFBLACK--DARKBLUE--LIGHTBLUE
POINT_COLOR_VISIBLE = OFFBLACK
POINT_LINE_COLOR = OFFBLACK--DARKBLUE
POINT_LINE_WIDTH = 1

VIEW_POINT_SIZE = 3
VIEW_POINT_COLOR = YELLOW--LIGHTRED 
VIEW_POINT_LINE_COLOR = OFFBLACK

--------------------------------
--  LINE SEGMENT 
--------------------------------
LINE_COLOR = ASBESTOS--OFFBLACK--DARKBLUE 
LINE_COLOR_VISIBLE = OFFBLACK
LINE_WIDTH = 1

--------------------------------
-- GRID
--------------------------------
GRID_LINE_COLOR = LIGHTGREY
GRID_LINE_WIDTH = 1
GRID_BOLDLINE_WIDTH = 2
GRID_ORIGO_WIDTH = 3
GRID_X = 10
GRID_Y = 10



--------------------------------
-- VIEW
--------------------------------
VIEWDISTANCE = 500
